apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: mayoclone
  labels:
    app.kubernetes.io/name: mayoclone-api
    app.kubernetes.io/part-of: mayoclone
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mayoclone-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
